"""
Interactive credential setup wizard for Facebook & Instagram
Helps users configure their .env file with proper credentials
"""

import os
from pathlib import Path


def print_header(text):
    """Print formatted header"""
    print("\n" + "="*60)
    print(text.center(60))
    print("="*60 + "\n")


def print_section(text):
    """Print section header"""
    print("\n" + "-"*60)
    print(text)
    print("-"*60)


def get_input(prompt, required=True, default=None):
    """Get user input with validation"""
    while True:
        if default:
            value = input(f"{prompt} [{default}]: ").strip()
            if not value:
                return default
        else:
            value = input(f"{prompt}: ").strip()

        if value or not required:
            return value

        print("❌ This field is required. Please enter a value.")


def setup_facebook_credentials():
    """Setup Facebook credentials"""
    print_section("📘 FACEBOOK CONFIGURATION")

    print("\nYou'll need:")
    print("  1. Facebook Page Access Token")
    print("  2. Facebook Page ID")
    print("\nSee docs/FACEBOOK_INSTAGRAM_SETUP.md for detailed instructions")

    proceed = input("\nDo you have these credentials ready? (yes/no): ").lower()
    if proceed != 'yes':
        print("\n⏭️  Skipping Facebook configuration")
        return None, None

    print("\n📝 Enter your Facebook credentials:")
    access_token = get_input("Facebook Page Access Token", required=True)
    page_id = get_input("Facebook Page ID", required=True)

    return access_token, page_id


def setup_instagram_credentials():
    """Setup Instagram credentials"""
    print_section("📷 INSTAGRAM CONFIGURATION")

    print("\nYou'll need:")
    print("  1. Instagram Access Token (same as Facebook Page Token)")
    print("  2. Instagram Business Account ID")
    print("\nNote: Instagram must be linked to your Facebook Page")

    proceed = input("\nDo you want to configure Instagram? (yes/no): ").lower()
    if proceed != 'yes':
        print("\n⏭️  Skipping Instagram configuration")
        return None, None

    use_same_token = input("\nUse same token as Facebook? (yes/no): ").lower()

    if use_same_token == 'yes':
        access_token = "SAME_AS_FACEBOOK"
    else:
        access_token = get_input("Instagram Access Token", required=True)

    account_id = get_input("Instagram Business Account ID", required=True)

    return access_token, account_id


def create_env_file(facebook_token, facebook_page_id, instagram_token, instagram_account_id):
    """Create or update .env file"""
    env_path = Path(".env")

    # Read existing .env if it exists
    existing_vars = {}
    if env_path.exists():
        with open(env_path, 'r') as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#') and '=' in line:
                    key, value = line.split('=', 1)
                    existing_vars[key.strip()] = value.strip()

    # Update with new values
    if facebook_token:
        existing_vars['FACEBOOK_ACCESS_TOKEN'] = facebook_token
    if facebook_page_id:
        existing_vars['FACEBOOK_PAGE_ID'] = facebook_page_id

    if instagram_token:
        if instagram_token == "SAME_AS_FACEBOOK":
            existing_vars['INSTAGRAM_ACCESS_TOKEN'] = facebook_token
        else:
            existing_vars['INSTAGRAM_ACCESS_TOKEN'] = instagram_token

    if instagram_account_id:
        existing_vars['INSTAGRAM_ACCOUNT_ID'] = instagram_account_id

    # Write .env file
    with open(env_path, 'w') as f:
        f.write("# Facebook & Instagram Configuration\n")
        f.write("# Generated by setup_credentials.py\n\n")

        f.write("# Facebook\n")
        f.write(f"FACEBOOK_ACCESS_TOKEN={existing_vars.get('FACEBOOK_ACCESS_TOKEN', '')}\n")
        f.write(f"FACEBOOK_PAGE_ID={existing_vars.get('FACEBOOK_PAGE_ID', '')}\n\n")

        f.write("# Instagram\n")
        f.write(f"INSTAGRAM_ACCESS_TOKEN={existing_vars.get('INSTAGRAM_ACCESS_TOKEN', '')}\n")
        f.write(f"INSTAGRAM_ACCOUNT_ID={existing_vars.get('INSTAGRAM_ACCOUNT_ID', '')}\n\n")

        # Add other existing variables
        other_vars = {k: v for k, v in existing_vars.items()
                     if k not in ['FACEBOOK_ACCESS_TOKEN', 'FACEBOOK_PAGE_ID',
                                 'INSTAGRAM_ACCESS_TOKEN', 'INSTAGRAM_ACCOUNT_ID']}

        if other_vars:
            f.write("# Other Configuration\n")
            for key, value in other_vars.items():
                f.write(f"{key}={value}\n")

    print(f"\n✅ Configuration saved to {env_path}")


def verify_credentials():
    """Verify credentials by running test script"""
    print_section("🔍 VERIFY CREDENTIALS")

    verify = input("\nDo you want to test the credentials now? (yes/no): ").lower()
    if verify != 'yes':
        print("\n⏭️  Skipping verification")
        print("\nYou can test later by running:")
        print("  python test_facebook_integration.py")
        return

    print("\n🧪 Running credential verification...")
    print("(This will test API connections without posting)\n")

    try:
        import subprocess
        result = subprocess.run(
            ["python", "test_facebook_integration.py"],
            capture_output=False,
            text=True
        )

        if result.returncode == 0:
            print("\n✅ Verification completed!")
        else:
            print("\n⚠️  Verification had some issues. Check the output above.")

    except Exception as e:
        print(f"\n❌ Could not run verification: {e}")
        print("\nPlease run manually:")
        print("  python test_facebook_integration.py")


def show_next_steps():
    """Show next steps after setup"""
    print_section("🚀 NEXT STEPS")

    print("\n1. Test your integration:")
    print("   python test_facebook_integration.py")

    print("\n2. Try the demo:")
    print("   python demo_facebook_watcher.py")

    print("\n3. Start the watcher:")
    print("   cd src")
    print("   python watcher_facebook.py")

    print("\n4. Or start all watchers:")
    print("   cd src")
    print("   python watcher.py")

    print("\n📚 Documentation:")
    print("   docs/FACEBOOK_INSTAGRAM_SETUP.md")

    print("\n💡 Tips:")
    print("   - Keep your tokens secure")
    print("   - Never commit .env to Git")
    print("   - Rotate tokens every 60 days")
    print("   - Monitor API rate limits")


def main():
    """Main setup wizard"""
    print_header("FACEBOOK & INSTAGRAM CREDENTIAL SETUP")

    print("This wizard will help you configure Facebook and Instagram")
    print("credentials for the AI Employee watcher system.")

    print("\n📋 Prerequisites:")
    print("  ✓ Facebook Business Account")
    print("  ✓ Facebook Page")
    print("  ✓ Instagram Business Account (optional)")
    print("  ✓ Facebook Developer App with required permissions")

    print("\n📖 For detailed setup instructions, see:")
    print("   docs/FACEBOOK_INSTAGRAM_SETUP.md")

    proceed = input("\nReady to start? (yes/no): ").lower()
    if proceed != 'yes':
        print("\n👋 Setup cancelled. Run this script again when ready!")
        return

    # Setup Facebook
    facebook_token, facebook_page_id = setup_facebook_credentials()

    # Setup Instagram
    instagram_token, instagram_account_id = setup_instagram_credentials()

    # Check if anything was configured
    if not facebook_token and not instagram_token:
        print("\n⚠️  No credentials configured. Exiting.")
        return

    # Create .env file
    print_section("💾 SAVING CONFIGURATION")
    create_env_file(facebook_token, facebook_page_id, instagram_token, instagram_account_id)

    # Verify credentials
    if facebook_token or instagram_token:
        verify_credentials()

    # Show next steps
    show_next_steps()

    print_header("SETUP COMPLETE!")
    print("\n🎉 Your Facebook & Instagram integration is ready!\n")


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\n⚠️  Setup interrupted by user")
        print("Run this script again to complete setup\n")
    except Exception as e:
        print(f"\n\n❌ Setup failed: {e}")
        print("Please check the error and try again\n")
