"""
Web Application Deployment Script

Automates web application deployment process including:
- Building production bundle
- Deploying to hosting platform
- Verifying deployment
- Generating deployment report

Usage:
    python deploy_webapp.py <app_directory>
    python deploy_webapp.py <app_directory> --platform <netlify|vercel|github-pages>
    python deploy_webapp.py --test  # Test mode
"""

import sys
import os
import subprocess
from pathlib import Path
from datetime import datetime


def build_production(app_dir):
    """Build production bundle."""
    print(f"Building production bundle for: {app_dir}")
    
    app_path = Path(app_dir)
    if not app_path.exists():
        print(f"Error: Directory not found: {app_dir}")
        return False
    
    # Check for package.json (Node.js project)
    package_json = app_path / "package.json"
    if package_json.exists():
        print("Detected Node.js project")
        try:
            # Install dependencies
            print("Installing dependencies...")
            subprocess.run(['npm', 'install'], cwd=app_dir, check=True)
            
            # Build
            print("Building...")
            subprocess.run(['npm', 'run', 'build'], cwd=app_dir, check=True)
            
            print("✓ Build successful")
            return True
        except subprocess.CalledProcessError as e:
            print(f"Error during build: {e}")
            return False
    else:
        print("No package.json found - assuming static HTML project")
        return True


def deploy_to_platform(app_dir, platform='netlify'):
    """Deploy to specified platform."""
    print(f"Deploying to {platform}...")
    
    if platform == 'netlify':
        print("⚠ Netlify deployment requires netlify-cli")
        print("  Install: npm install -g netlify-cli")
        print("  Deploy: netlify deploy --prod")
        return False
    
    elif platform == 'vercel':
        print("⚠ Vercel deployment requires vercel-cli")
        print("  Install: npm install -g vercel")
        print("  Deploy: vercel --prod")
        return False
    
    elif platform == 'github-pages':
        print("⚠ GitHub Pages deployment requires gh-pages")
        print("  Install: npm install -g gh-pages")
        print("  Deploy: gh-pages -d build")
        return False
    
    else:
        print(f"Error: Unknown platform: {platform}")
        return False


def verify_deployment(url):
    """Verify deployment is successful."""
    print(f"Verifying deployment at: {url}")
    
    try:
        import requests
        response = requests.get(url, timeout=10)
        if response.status_code == 200:
            print("✓ Deployment verified - site is live")
            return True
        else:
            print(f"⚠ Site returned status code: {response.status_code}")
            return False
    except ImportError:
        print("⚠ requests library not installed - skipping verification")
        print("  Install: pip install requests")
        return False
    except Exception as e:
        print(f"Error verifying deployment: {e}")
        return False


def generate_deployment_report(app_dir, platform, success, output_path):
    """Generate deployment report."""
    md = f"""# Deployment Report
**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

---

## Deployment Details

- **Application:** `{app_dir}`
- **Platform:** {platform}
- **Status:** {'✓ SUCCESS' if success else '✗ FAILED'}

## Build Process

"""
    
    if success:
        md += "✓ Production bundle built successfully\n"
    else:
        md += "✗ Build failed - see logs for details\n"
    
    md += f"""
## Deployment Steps

1. Build production bundle
2. Deploy to {platform}
3. Verify deployment

## Next Steps

"""
    
    if success:
        md += """- Monitor application performance
- Check error logs
- Verify all features working correctly
"""
    else:
        md += """- Review build logs for errors
- Fix any build issues
- Retry deployment
"""
    
    md += "\n---\n\n*Generated by Web Executor skill*\n"
    
    # Save report
    output_file = Path(output_path)
    output_file.parent.mkdir(parents=True, exist_ok=True)
    
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(md)
    
    print(f"✓ Deployment report saved to: {output_path}")


def main():
    """Main execution function."""
    if '--test' in sys.argv:
        print("Running in TEST mode...")
        print("\nThis script automates web application deployment.")
        print("\nSupported platforms:")
        print("  - Netlify")
        print("  - Vercel")
        print("  - GitHub Pages")
        print("\nGenerating sample deployment report...")
        
        output_path = "02_Pending_Approval/test_deployment_report.md"
        generate_deployment_report("./sample-app", "netlify", True, output_path)
        
        print("\n✓ Test complete!")
        return
    
    if len(sys.argv) < 2:
        print("Usage:")
        print("  python deploy_webapp.py <app_directory>")
        print("  python deploy_webapp.py <app_directory> --platform <netlify|vercel|github-pages>")
        print("  python deploy_webapp.py --test")
        sys.exit(1)
    
    app_dir = sys.argv[1]
    
    # Determine platform
    platform = 'netlify'  # default
    if '--platform' in sys.argv:
        platform_idx = sys.argv.index('--platform') + 1
        if platform_idx < len(sys.argv):
            platform = sys.argv[platform_idx]
    
    print(f"Deploying: {app_dir}")
    print(f"Platform: {platform}")
    print()
    
    # Build
    build_success = build_production(app_dir)
    
    if not build_success:
        print("\n✗ Build failed - aborting deployment")
        output_path = f"02_Pending_Approval/deployment_failed_{datetime.now().strftime('%Y%m%d_%H%M%S')}.md"
        generate_deployment_report(app_dir, platform, False, output_path)
        sys.exit(1)
    
    # Deploy
    deploy_success = deploy_to_platform(app_dir, platform)
    
    # Generate report
    output_path = f"02_Pending_Approval/deployment_{platform}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.md"
    generate_deployment_report(app_dir, platform, deploy_success, output_path)
    
    if deploy_success:
        print("\n✓ Deployment complete!")
    else:
        print("\n⚠ Deployment incomplete - manual steps required")


if __name__ == "__main__":
    main()
